[tool.black]
line-length = 88
skip-string-normalization = false

[tool.ruff]
line-length = 88
select = ["E", "F", "I", "B"]
ignore = []

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
